---
title: "week9"
output: html_document
---

```{r}
# 第一型
zscore<-seq(-3,3,0.1)
pvalues<-pnorm(zscore)
plot(zscore,pvalues)
```

```{r}
# 第二型
zscore<-seq(-3,3,0.1)
pvalues<-pnorm(zscore)
plot(zscore,pvalues,type="l")
```

```{r}
# 第三型(待偵錯)
zscore<-seq(-3,3,0.1)
pvalues<-pnorm(zscore)
plot(pvalues,type="l",xaxt="n")
oo<-rep(F,length(zscore))
oo[3]<-T

axis(1,at=which(oo),label="this")
```


```{r}

uu<-seq(0,1,length=100)
#從0~1生成100筆等間隔數據
uu<-uu[c(-1,-100)]
# uu[c(-1,-100)]表刪除掉uu數列中第1筆與第100筆資料
z_scores<-qnorm(uu)
pvalues<-pnorm(z_scores)
plot(z_scores,pvalues,type="l",xlab="z-scores",
     ylab="Probility",xaxt="n",main="CDF",
     ylim=c(0.0,1.0))

axis(1,at=which(round(pvalues,2)==0.2),label=round(qnorm(0.2),2))
# 如果要把y軸改成間隔0.1？axis(2,0.1)失敗

```













# 標準差佔的信賴區間百分比
# pnorm(1)表zscore(z分數)從負無限大至1的機率
```{r}
# Z分數-1~1佔0.68
right<-pnorm(1)
left<-pnorm(-1)
print(right-left)
```

```{r}
# Z分數-2~2佔0.95
right<-pnorm(2)
left<-pnorm(-2)
print(right-left)
```

```{r}
# Z分數-k~k信賴區間公式化
percentbysd<-function(sd){
  right<-pnorm(sd)
  left<-pnorm(-sd)
  return(right-left)
}
percentbysd(1)
percentbysd(2)
percentbysd(3)
```


# 我要寫一個函數，用來過濾-2到2之間的值
```{r}
# 第一型
myfilter<-function(x){
  rst<-x<=0.2
  le2<-x[rst]
  rst2<-le2>=-0.2
  xx<-le2[rst2]
  return(xx)
}
x<-rnorm(10)
myfilter(x)
```

```{r}
# 第二型
myfilter<-function(x,min,max){
  rst<-x<=max
  le2<-x[rst]
  rst2<-le2>=min
  xx<-le2[rst2]
  return(xx)
}
x<-rnorm(10)
myfilter(x,min=-0.2,max=0.2)
```

```{r}
# 第三型
myfilter<-function(x,min,max){
  rst<-x<=max
  le2<-x[rst]
  rst2<-le2>=min
  xx<-le2[rst2]
  return(xx)
}
x<-rnorm(10)
myfilter(x,-0.2,0.2)
```

```{r}
# 第四型
myfilter<-function(x){
  le2<-x[x<=0.2]
  xx<-le2[le2>=-0.2]
  return(xx)
}
x<-rnorm(10)
myfilter(x)
```

# 給我一個向量，要排出偶數
```{r}
# poisson分配以lambda=2的情況下挑30個數
x<-rpois(30,2)
#列出x
x
#被2整除=T，不被2整除=F
x%%2==0
#挑出被2整除的x
x[x%%2==0]
#挑出被2整除的x是在第幾個
which(x%%2==0)

geteven<-function(v){
  return(v[v%%2==0])
}
x
geteven(x)
```

